name: presence
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.6
  cloud_firestore: ^4.17.4
  firebase_storage: ^11.7.6
  image_picker: 1.1.1
  convex_bottom_bar: 3.2.0
  intl: 0.19.0
  geolocator: 12.0.0
  geocoding: 3.0.0
  flutter: 
    sdk: flutter
  syncfusion_flutter_datepicker: ^25.2.7

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_launcher_icons: "^0.13.1"
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

