// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7U5IYIFyDTkbA750OfT3kHM-pxEPk9Uo',
    appId: '1:139931262767:web:1af80ca798315773cecbda',
    messagingSenderId: '139931262767',
    projectId: 'kerjolee-264f0',
    authDomain: 'kerjolee-264f0.firebaseapp.com',
    storageBucket: 'kerjolee-264f0.appspot.com',
    measurementId: 'G-812QZ37KHW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_y7tGlQITnZjH2wjwToFqqzILcStl3Sc',
    appId: '1:139931262767:android:c8b74f233b488dd1cecbda',
    messagingSenderId: '139931262767',
    projectId: 'kerjolee-264f0',
    storageBucket: 'kerjolee-264f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt5IqmAdJbgwLochG9OQI34rw7rdj7NwA',
    appId: '1:139931262767:ios:dca8d6c28ce06722cecbda',
    messagingSenderId: '139931262767',
    projectId: 'kerjolee-264f0',
    storageBucket: 'kerjolee-264f0.appspot.com',
    iosBundleId: 'com.kerjolee.presence',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt5IqmAdJbgwLochG9OQI34rw7rdj7NwA',
    appId: '1:139931262767:ios:dca8d6c28ce06722cecbda',
    messagingSenderId: '139931262767',
    projectId: 'kerjolee-264f0',
    storageBucket: 'kerjolee-264f0.appspot.com',
    iosBundleId: 'com.kerjolee.presence',
  );
}
